version: '3.4'

services:
  simplenetcoreapp:
    image: ${DOCKER_REGISTRY}simplenetcoreapp
    build:
      context: .
      dockerfile: SIMPLENETCOREAPP/Dockerfile
    ports:
      - "12345:22"
    security_opt:
      - seccomp:unconfined
